services:
  profile-service:
    build: .
    container_name: profile-service
    ports:
      - "8081:8081"
    env_file:
      - ../.env_docker
    networks:
      - app-network

networks:
  app-network:
    name: social-network
    driver: bridge
    external: true


