spring:
  application:
    name: ${EUREKA_NAME}
server:
  port: ${EUREKA_PORT}
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF