server:
  port: 8888
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  data:
    redis:
      host: localhost # Địa chỉ Redis
      port: 6379 # Cổng Redis
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Kích hoạt định tuyến tự động dựa trên tên service từ Eureka
      routes:
        - id: identity_service
          uri: lb://IDENTIFY
          predicates:
          - Path=/identity/**
          filters:
#          - StripPrefix=2

        - id: profile_service
          uri: lb://PROFILE
          predicates:
          - Path=/profile/**
          filters:
#          - StripPrefix=

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/