server:
  port: 8888
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: identity_service
          uri: http://localhost:8080
          predicates:
          - Path=/identity/**
          filters:
#          - StripPrefix=2

        - id: profile_service
          uri: http://localhost:9000
          predicates:
          - Path=/QuanLyBaiDoXe/api/users/**
          filters:
#          - StripPrefix=

        - id: other_service
          uri: http://localhost:9000
          predicates:
            - Path=/public/QuanLyBaiDoXe/api/**
          filters:
          - StripPrefix=1

        - id: admin_service
          uri: http://localhost:8800
          predicates:
            - Path=/admin/**
          filters:
#            - StripPrefix=1