server:
  port: ${GATEWAY_PORT}
app:
  api-prefix: ${API_PREFIX}

spring:
  application:
    name:  ${GATEWAY_APPLICATION_NAME}
  data:
    redis:
      host: ${GATEWAY_REDIS_HOST}
      port: ${GATEWAY_REDIS_PORT}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
          #http://identity-service:8080
        - id: identity_service
          uri: lb://${IDENTITY_SERVICE}
          predicates:
          - Path=/identity/**
        #  lb://${PROFILE_SERVICE}
        #http://profile-service:8081
        - id: profile_service
          uri: lb://${PROFILE_SERVICE}
          predicates:
            - Path=/profile/**

        - id: friend_service
          uri: lb://${FRIEND_SERVICE}
          predicates:
            - Path=/friend/**

        - id: notification_service
          uri: lb://${NOTIFICATION_SERVICE}
          predicates:
            - Path=/notification/**

        - id: post_service
          uri: lb://${POST_SERVICE}
          predicates:
            - Path=/post/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}

IDENTIFY_URL: ${IDENTIFY_URL}
