server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/social_identity"
    username: root
    password: ngoquang178
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



rabbit:
  queue:
    google: googleAuthQueue


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  services:
    common: http://localhost:9000/QuanLyBaiDoXe/api/
    faceAuth: http://127.0.0.1:8000/


redis:
  host: redis://localhost:6379