server:
  port: ${IDENTIFY_PORT:8080}
  servlet:
    context-path: ${IDENTIFY_CONTEXT_PATH:/identity}

spring:
  application:
    name: ${IDENTIFY_APP_NAME:IDENTIFY}
  datasource:
    url: jdbc:mysql://${IDENTIFY_DB_HOST:localhost}:${IDENTIFY_DB_PORT:3306}/${IDENTIFY_DB_NAME:social_identity}
    username: ${IDENTIFY_DB_USERNAME}
    password: ${IDENTIFY_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  rabbitmq:
    host: ${IDENTIFY_RABBITMQ_HOST:localhost}
    port: ${IDENTIFY_RABBITMQ_PORT:5672}
    username: ${IDENTIFY_RABBITMQ_USERNAME:guest}
    password: ${IDENTIFY_RABBITMQ_PASSWORD:guest}

rabbit:
  queue:
    google: ${IDENTIFY_RABBITMQ_QUEUE_GOOGLE:googleAuthQueue}

jwt:
  signerKey: ${IDENTIFY_JWT_SIGNER_KEY}

app:
  services:
    information: ${IDENTIFY_SERVICE_INFORMATION:http://localhost:8081/profile/}
    faceAuth: ${IDENTIFY_SERVICE_FACEAUTH:http://127.0.0.1:8000/}

redis:
  host: ${REDIS_URL:redis://localhost:6379}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    hostname: localhost

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  secure: true