server:
  port: ${PROFILE_PORT:8081}
  servlet:
    context-path: ${PROFILE_CONTEXT_PATH:/profile}

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ${PROFILE_APP_NAME:PROFILE}
  datasource:
    url: jdbc:mysql://${PROFILE_DB_HOST:localhost}:${PROFILE_DB_PORT:3306}/${PROFILE_DB_NAME:socialuserinformation}
    username: ${PROFILE_DB_USERNAME}
    password: ${PROFILE_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: ${PROFILE_RABBITMQ_HOST:localhost}
    port: ${PROFILE_RABBITMQ_PORT:5672}
    username: ${PROFILE_RABBITMQ_USERNAME:guest}
    password: ${PROFILE_RABBITMQ_PASSWORD:guest}
#  ai:
#    vectorstore:
#      qdrant:
#        host: 8ba05ff2-6fe7-4eee-beae-abb90e95eaa8.europe-west3-0.gcp.cloud.qdrant.io
#        port: 6333
#        api-key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0._LrWJcEy6RTX1i-q_JHJVwdP_e6yDp91A_36CiDuaY4
#        collection-name: friend_suggestion
#        use-tls: true
rabbit:
  queue:
    google: ${PROFILE_RABBITMQ_QUEUE_GOOGLE:googleAuthQueue}

jwt:
  signerKey: ${PROFILE_JWT_SIGNER_KEY:1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij}

app:
  services:
    identity: ${PROFILE_SERVICE_IDENTITY:http://localhost:8080/identity/}

redis:
  host: ${REDIS_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
    enabled: true
  instance:
    hostname: localhost

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
  secure: true

openai:
  api:
    key: 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
  embedding:

  user-id: spring-ai-user