server:
  port: 8081
  servlet:
    context-path: /profile

spring:
  application:
    name: PROFILE
  datasource:
    url: "jdbc:mysql://localhost:3306/socialuserinformation"
    username: root
    password: ngoquang178
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest



rabbit:
  queue:
    google: googleAuthQueue


jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  services:
    identity: http://localhost:8080/identity/


redis:
  host: redis://localhost:6379

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Địa chỉ của Eureka Server
    register-with-eureka: true # Tùy chọn, nếu bạn muốn ứng dụng cũng đăng ký
    fetch-registry: true # Bắt buộc để lấy thông tin từ Eureka
    enabled: true
  instance:
    hostname: localhost
#    prefer-ip-address: true # Sử dụng IP thay vì hostname