version: "3"
services:
  redis:
    image: 'bitnami/redis:6.2.16-debian-12-r3'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", 'redis-cli', "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "6379:6379"
    volumes:
      - social_volume_identity:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

volumes:
  social_volume_identity:
    external: true  # Đảm bảo rằng volume này đã tồn tại trên Docker