services:
  redis:
    container_name: redis
    image: 'bitnami/redis:6.2.16-debian-12-r3'
    restart: 'unless-stopped'
    healthcheck:
      test: ["CMD", 'redis-cli', "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "6379:6379"
    volumes:
      - social_volume_identity:/bitnami/redis/data
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

  eureka:
    image: jhipster/jhipster-registry
    container_name: eureka
    ports:
      - "8761:8761"
    environment:
      - JHIPSTER_REGISTRY_PASSWORD=admin
    networks:
      - app-network
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app-network
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: "social_identity"
    ports:
      - "3306:3306"
    networks:
      - app-network

  identity-service:
    container_name: identity
    image: 'truongglitt/indentity-service:0.0.1'
    ports:
      - "8080:8080"
    env_file:
      - ./.env_docker
    networks:
      - app-network

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"   # REST API
      - "6334:6334"   # gRPC API
    volumes:
      - qdrant_storage:/qdrant/storage
    restart: unless-stopped
    networks:
      - app-network

volumes:
  qdrant_storage:
  social_volume_identity:
    external: true  # Đảm bảo rằng volume này đã tồn tại trên Docker

networks:
  app-network:
    name: social-network
    driver: bridge
